language: java
sudo: false
addons:
          apt:
                    sources: r-packages-precise
                    packages: 
                              - gcc-4.9-arm-linux-gnueabi


install: 
          - ls /bin
          - mvn clean install -Dcompiler.exec=arm-linux-gnueabihf-gcc-4.8 -Dlinker.exec=arm-linux-gnueabihf-ld

jdk:
          - oraclejdk8

