language: java
sudo: false
addons:
          apt:
                    sources: r-packages-trusty
                    packages: gcc-4.8-arm-linux-gnueabihf 


install: mvn clean install -Dcompiler.exec=arm-linux-gnueabihf-gcc-4.8 -Dlinker.exec=arm-linux-gnueabihf-ld

jdk:
          - oraclejdk8

